### ISSUE TITLE
Doesn't work with polygon

### ISSUE THREAD

**Issue by ahalota** [jieter/leaflet-clonelayer#2]
I've tested this with Rectangle and Polygon.
I am making a clone of my layer, and editing its latlng values.

With rectangle, no problem, does not affect the original layer.
For polygon, it moves the new layer as well. Doesn't seem to actually clone. as the O.LatLngs in _latlng array are the same ones from the original. Need to add a step to create copies of each of these.

**Comment by jieter** [comment]
@ahalota thanks for reporting. Can you make a jsfiddle/[playground-leaflet](https://playground-leaflet.rhcloud.com/vup/edit?html,output) to show the problem? I tried reproducing it, but did not succeed doing that using the public API (`setLatLngs()`).

Are you accessing/changing the `polygon._latlngs` array?

**Comment by jieter** [comment]
@ahalota any news?

**Comment by jieter** [comment]
I'm closing this for the lack of a proper example. If you experience the problem, please provide a 
[minimal working example](https://stackoverflow.com/help/mcve) in playground-leaflet or jsfiddle
