### ISSUE TITLE
Consider renderer when cloning layers using leaflet version >= 1.0.0

### ISSUE THREAD

**Issue by JoHae** [jieter/leaflet-clonelayer#3]
If you clone a layer that has a renderer set e.g. `options.renderer = L.canvas()`, cloning the layer and adding it to another map results in the deletion of the dedicated layer in the original map.
To reproduce this issue:

1. Init 2 Maps. Set the default renderer of both maps to L.canvas()
2. Add a geoJson Layer to one map using renderer: L.svg()
3. Clone the layer and add it to the other map
4. Call e.g. map2.fitBounds(polygon.getBounds())

The polygon disappears completely from the first map. If you cannot reproduce it, i can provide a jsfiddle. I did a workaround (which seems to work):

```JavaScript
let renderer;
if(layer.options.renderer instanceof L.svg) {
  renderer = L.svg();
} else {
  renderer = L.canvas();
}
let clone = clonelayer(layer);
clone.options.renderer = renderer;
map2.addLayer(clone);
```

**Comment by jieter** [comment]
You are right, I think it's fixed by 39661b6, can you please verify?
