### ISSUE TITLE
Support for common plugins

### ISSUE THREAD

**Issue by jieter** [jieter/leaflet-clonelayer#4]
- https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant (refs jieter/Leaflet.layerscontrol-minimap/issues/7)
- https://github.com/Leaflet/Leaflet.markercluster

**Comment by giovanism** [comment]
Any update on this or plan for eventual support? I would like to help with a few guide/directions as to how support this. I will work on L.GridLayer.GoogleMutant support.

**Comment by giovanism** [comment]
More or less these right?

> - check if L.GridLayer.GoogleMutant is defined (to make sure leaflet-clonelayer still works when not used together with Google Mutant.
> - check if the layer is a Google Mutant layer: layer instanceof L.GridLayer.GoogleMutant.
> - return a cloned version of the Google Mutant layer: return L.gridLayer.googleMutant(layer.options);

**Comment by jieter** [comment]
@giovanism that's right!
